// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartShoppingAssistant.DataAccess;

#nullable disable

namespace SmartShoppingAssistant.DataAccess.Migrations
{
    [DbContext(typeof(SmartShoppingAssistantDbContext))]
    [Migration("20260510133022_SeedInitialData1")]
    partial class SeedInitialData1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductCategories", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            CategoriesId = 1,
                            ProductsId = 1
                        },
                        new
                        {
                            CategoriesId = 1,
                            ProductsId = 2
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 3
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 4
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems", (string)null);
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Gadgets and tech devices",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Daily food and essentials",
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Apparel and accessories",
                            Name = "Clothing"
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ergonomic wireless mouse",
                            ImageUrl = "",
                            Name = "Wireless Mouse",
                            Price = 25.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "High performance laptop",
                            ImageUrl = "",
                            Name = "Gaming Laptop",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Freshly baked",
                            ImageUrl = "",
                            Name = "Whole Wheat Bread",
                            Price = 3.49m
                        },
                        new
                        {
                            Id = 4,
                            Description = "1 lb of Fuji apples",
                            ImageUrl = "",
                            Name = "Apples",
                            Price = 4.99m
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Reward")
                        .HasColumnType("int");

                    b.Property<int>("RewardValue")
                        .HasColumnType("int");

                    b.Property<decimal>("Threshold")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("Promotions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = false,
                            Name = "15% off Laptops",
                            ProductId = 2,
                            Reward = 0,
                            RewardValue = 15,
                            Threshold = 0m,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            IsActive = false,
                            Name = "Buy 2 Apples Get 1 Free",
                            ProductId = 4,
                            Reward = 1,
                            RewardValue = 0,
                            Threshold = 2m,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            IsActive = false,
                            Name = "10% off all Groceries over $50",
                            Reward = 0,
                            RewardValue = 10,
                            Threshold = 50.00m,
                            Type = 0
                        });
                });

            modelBuilder.Entity("ProductCategories", b =>
                {
                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.CartItem", b =>
                {
                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Promotion", b =>
                {
                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Category", "Category")
                        .WithMany("Promotions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Product", "Product")
                        .WithMany("Promotions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Category", b =>
                {
                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Product", b =>
                {
                    b.Navigation("Promotions");
                });
#pragma warning restore 612, 618
        }
    }
}
